using System;
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// This file is automatically generated
[System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
public static class VersionInfo
{
    public static string Version => "0.1.1-beta0009";
    public static string CommitInfo => "Branch.develop.Sha.e68f6ff93fa5f6056b8cfa63d82082797669a483";
    public static string CommitDate => "2022-05-24";
    public static string CommitHash => "e68f6ff93fa5f6056b8cfa63d82082797669a483";
    public static string InformationalVersion => "0.1.1-beta.9+Branch.develop.Sha.e68f6ff93fa5f6056b8cfa63d82082797669a483";
    public static DateTime BuildDateUtc => new DateTime(2022, 5, 24, 15, 16, 35, DateTimeKind.Utc);
}
